# Generated by Django 5.2.8 on 2026-08-22 13:52

import django.db.models.deletion
import hiring_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleoauthtoken',
            name='token_json',
            field=hiring_app.models.EncryptedTextField(help_text='Google OAuth2 credentials as JSON string, encrypted at rest'),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='New Campaign', max_length=200)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('jd_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('form_id', models.CharField(blank=True, max_length=255)),
                ('form_url', models.URLField(blank=True)),
                ('sheet_id', models.CharField(blank=True, max_length=255)),
                ('sheet_url', models.URLField(blank=True)),
                ('drive_qid', models.CharField(blank=True, max_length=255)),
                ('email_qid', models.CharField(blank=True, max_length=255)),
                ('linkedin_post_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_response_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('drive_link', models.URLField(blank=True)),
                ('file_id', models.CharField(blank=True, max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('text_preview', models.TextField(blank=True)),
                ('download_status', models.CharField(choices=[('no_link', 'No Link'), ('unrecognised_link', 'Unrecognised Link'), ('downloaded', 'Downloaded'), ('download_failed', 'Download Failed')], default='no_link', max_length=20)),
                ('download_attempts', models.PositiveSmallIntegerField(default=0)),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_type', models.CharField(blank=True, choices=[('', 'Pending'), ('offer', 'Offer Sent'), ('rejected', 'Rejected')], default='', max_length=10)),
                ('outcome_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='hiring_app.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'email'), name='unique_candidate_email_per_campaign')],
            },
        ),
    ]
