# Generated by Django 5.2.8 on 2026-08-22 13:56

import hiring_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0003_encrypt_legacy_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, upload_to=hiring_app.models.candidate_resume_path),
        ),
    ]
