# Generated by Django 5.2.8 on 2026-09-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0005_apply_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='retention_days',
            field=models.PositiveIntegerField(default=180),
        ),
    ]
