# Generated by Django 5.2.8 on 2026-09-05 16:40

import django.db.models.deletion
import hiring_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0006_campaign_retention_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_json', hiring_app.models.EncryptedTextField(help_text='LinkedIn OAuth2 access token + member URN, JSON, encrypted at rest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
